### ISSUE TITLE
Support for 'Meas3Ranges' sbf block

### ISSUE THREAD

**Issue by Wolfz28** [MJeanneRose/sbfParser#2]
Greetings,

I have a Septentrio Mosaic X-5 receiver and I'm trying to parse the observation and navigation data from a sbf file from that receiver in order to use them for positioning. However, the observation data that I'm looking for is in the 'Meas3Ranges' block and this library doesn't seem to support the acquisition of said block (it just provides an empty dictionary). 

On that note, will this library support that block in the future? Right now, this is the only reliable library that does what I want to achieve.

Best regards.

**Comment by MJeanneRose** [comment]
Hello Wolfz28,

I used the Reference Guide V4.14 to build this parser and it doesn't provide enough information about Meas3Ranges blocks.
If you can't use the MeasEpoch blocks instead, take a look at RxTools

`The RxTools installation contains the complete source code of a decoder in C language[...]. All C files can be found under the
sbf2asc folder in the RxTools installation. The main measurement decoding function is
sbfread_MeasCollectAndDecode() in the sbfread_meas.c file.`

I don't plan to update in the near futur

Best regards,

**Comment by Wolfz28** [comment]
Hello MJeanneRose,

Thank you for the response, I will see what I can do.

Best regards,
