### ISSUE TITLE
Support for a real-time data stream

### ISSUE THREAD

**Issue by GOT4BRG** [MJeanneRose/sbfParser#3]
Greetings,

Will this library have support for a Septentrio's receiver real-time data stream in the future, in order to use the observation and navigation data to calculate a position?

Best regards.

**Comment by MJeanneRose** [comment]
Hello,

My project ended so I don't plan to do any update for the moment.

Following the speed and the configuration of your receiver you can call **sbf_parser.load(**_your_stream_**)** every X times

Best regards,
